package net.hubtangle.auth

/**
 * Represents security role in Hubtangle.
 * <br> Generated by spring-security-plugin
 * 
 * @author mkubryn
 */
class SecRole {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}
